baseURL = "http://www.0less1.com/"
languageCode = "en-us"
title = "0 < 1"
theme = "ezhil"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-140454003-1"
disqusShortname = "localhost"

[params]
	subtitle = "Mathematics & Computer Science concepts explained ∀∞"
	# Number of posts to show in recent posts list.
	recentPostsCount = 50
	# Content types which are excluded from recent posts and archive page.
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
  
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/mieroo/0less1"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/miero/"

[[params.social]]
name = "YouTube"
icon = "youtube"
url = "https://www.youtube.com/channel/UCKA35yUAVwl85uMc4UHKPqA?view_as=subscriber"

[taxonomies]
   tag = "tags"
